<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BoligInfo.Core\BoligInfo.Core.csproj" />
      <ProjectReference Include="..\..\BoligInfo.Repositories\BoligInfo.CashFlowRepository\BoligInfo.CashFlowRepository.csproj" />
      <ProjectReference Include="..\..\BoligInfo.Repositories\BoligInfo.EquityRepository\BoligInfo.EquityRepository.csproj" />
      <ProjectReference Include="..\..\BoligInfo.Repositories\BoligInfo.HouseRepository\BoligInfo.HouseRepository.csproj" />
    </ItemGroup>

</Project>
